[project]
name = 'Energy-Grid-Insurance-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.grid-outage-monitor]
path = 'contracts/grid-outage-monitor.clar'
clarity_version = 3
epoch = '3.2'

[contracts.production-loss-calculator]
path = 'contracts/production-loss-calculator.clar'
clarity_version = 3
epoch = 'latest'

[contracts.weather-generation-oracle]
path = 'contracts/weather-generation-oracle.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
